DELIMITER $$
CREATE PROCEDURE SetBCSYS_ATIVO(
	IN  pATV_CODIGO VARCHAR(20)
	,pATV_DES_ULT  VARCHAR(50)
	,pATV_DES_FEC  VARCHAR(50))
BEGIN
	UPDATE BCSYS_ATIVO
		SET ATV_DAT_DATAHORA=NOW()
		,ATV_DES_ULT=IFNULL(pATV_DES_ULT,ATV_DES_ULT)
		,ATV_DES_FEC=IFNULL(pATV_DES_FEC,ATV_DES_FEC)
		WHERE ATV_CODIGO=pATV_CODIGO;
	IF ROW_COUNT()=0 THEN
		INSERT INTO BCSYS_ATIVO (ATV_CODIGO,ATV_DAT_DATAHORA,ATV_DES_ULT,ATV_DES_FEC)
			VALUES (pATV_CODIGO,NOW(),pATV_DES_ULT,pATV_DES_FEC);
	END IF;
END$$
DELIMITER ;
