CREATE TABLE BCSYS_NEGOCIO_TEMP
(
TS_CODIGO VARCHAR(20) NOT NULL,
TS_DESC VARCHAR(50) NULL,
TS_DATA VARCHAR(50) NULL,
TS_HORA VARCHAR(50) NULL,
TS_TIPO VARCHAR(50) NULL,
TS_PRECO VARCHAR(50) NULL,
TS_QTD VARCHAR(50) NULL,
TS_AG_CP VARCHAR(50) NULL,
TS_AG_VD VARCHAR(50) NULL,
INDEX TS_CODIGO (TS_CODIGO),
INDEX TS_DATA (TS_DATA)
);
/*
Tabela BCSYS_NEGOCIO_TEMP transferida no horário configurado INSERT INTO BCSYS_NEGOCIO SELECT * FROM BCSYS_NEGOCIO_TEMP WHERE TS_DATA<$DATA
*/
CREATE TABLE BCSYS_NEGOCIO
(
TS_CODIGO VARCHAR(20) NOT NULL,
TS_DESC VARCHAR(50) NULL,
TS_DATA VARCHAR(50) NULL,
TS_HORA VARCHAR(50) NULL,
TS_TIPO VARCHAR(50) NULL,
TS_PRECO VARCHAR(50) NULL,
TS_QTD VARCHAR(50) NULL,
TS_AG_CP VARCHAR(50) NULL,
TS_AG_VD VARCHAR(50) NULL,
INDEX TS_CODIGO (TS_CODIGO),
INDEX TS_DATA (TS_DATA)
);

