CREATE TABLE BCSYS_TS_TEMP (
	TS_CODIGO VARCHAR(10) NULL,
	TS_DESC VARCHAR(50) NULL,
	TS_DATA VARCHAR(20) NULL,
	TS_HORA VARCHAR(20) NULL,
	TS_TIPO VARCHAR(20) NULL,
	TS_PRECO VARCHAR(20) NULL,
	TS_QTD VARCHAR(20) NULL,
	TS_AG_CP VARCHAR(50) NULL,
	TS_AG_VD VARCHAR(50) NULL,
	PRIMARY KEY (TS_CODIGO)
);
CREATE TABLE BCSYS_TS_FINAL (
	TS_CODIGO VARCHAR(10) NULL,
	TS_DESC VARCHAR(50) NULL,
	TS_DATA VARCHAR(20) NULL,
	TS_HORA VARCHAR(20) NULL,
	TS_TIPO VARCHAR(20) NULL,
	TS_PRECO VARCHAR(20) NULL,
	TS_QTD VARCHAR(20) NULL,
	TS_AG_CP VARCHAR(50) NULL,
	TS_AG_VD VARCHAR(50) NULL,
	PRIMARY KEY (TS_CODIGO)
);
